import type { ExpoConfig } from 'expo/config';

/**
 * Time Served — app config.
 *
 * The app name and the deep-link scheme live here (see CLAUDE.md preamble).
 * Grep for `timeserved` / `Time Served` before renaming anything.
 */
const config: ExpoConfig = {
  name: 'Time Served',
  slug: 'time-served',
  version: '0.1.0',
  orientation: 'portrait',
  // J11: assets generated by scripts/generate-icons.mjs (flat lid+box glyph,
  // sun-yellow/moon-blue split on deep slate — theme colors).
  icon: './assets/icon.png',
  // The ui/theme has full light+dark palettes (J8) — follow the system.
  userInterfaceStyle: 'automatic',
  // Deep-link scheme: invite links + NFC tag URIs (`timeserved://box/<uuid>?v=1`).
  scheme: 'timeserved',
  android: {
    package: 'koeln.gebauer.timeserved',
    adaptiveIcon: {
      backgroundColor: '#1D2530',
      foregroundImage: './assets/android-icon-foreground.png',
      backgroundImage: './assets/android-icon-background.png',
      monochromeImage: './assets/android-icon-monochrome.png',
    },
    predictiveBackGestureEnabled: false,
    // J10: https invite links (`https://timeserved.app/j#…`) offer the app in
    // the Android chooser. Unverified (no assetlinks.json yet — J11 hardening
    // can add autoVerify); the timeserved:// scheme works regardless.
    intentFilters: [
      {
        action: 'VIEW',
        category: ['BROWSABLE', 'DEFAULT'],
        data: [{ scheme: 'https', host: 'timeserved.app', pathPrefix: '/j' }],
      },
    ],
  },
  ios: {
    // iOS is a later adapter swap (BUILD_V1 §13); config kept minimal but valid.
    supportsTablet: false,
  },
  plugins: [
    './plugins/nfc',
    './plugins/fgs',
    // J11: status-bar notification icon must be white-on-transparent — the
    // monochrome glyph is exactly that. Accent: sun-yellow (theme `day`).
    [
      'expo-notifications',
      {
        icon: './assets/android-icon-monochrome.png',
        color: '#F5B942',
      },
    ],
    // J11: splash — glyph on theme background, light and dark.
    [
      'expo-splash-screen',
      {
        image: './assets/splash-icon.png',
        imageWidth: 160,
        resizeMode: 'contain',
        backgroundColor: '#F4F5F7',
        dark: { backgroundColor: '#12161C' },
      },
    ],
  ],
};

export default config;
